### ISSUE TITLE
x1dcorr: doDqicorr() missing 2 required positional arguments: 'traceprofile' and 'gti'

### ISSUE THREAD

**Issue by parkus** [spacetelescope/costools#22]
I'm attempting to produce some sub-exposure COS x1d files and am hitting  a TypeError when I try to run `x1dcorr`. `splittag` works fine and produces the relevant corrtag files. But trying to take one set of the subexposure corrtag files and process them into an x1d like so

```
from costools import x1dcorr
x1dcorr.x1dcorr(["test_1_corrtag_a.fits", "test_1_corrtag_b.fits"], outdir="test/", update_input=True, find=True, verbosity=2)
```

throws this 

```
Input     /Users/parke/Google Drive/Research/dimming/data/test_1_corrtag_a.fits
OutFlt    test/test_1_flt_a.fits
OutCounts test/test_1_counts_a.fits
x1d       test/test_1_x1d_a.fits

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-66f3f7e5ffe2> in <module>
----> 1 x1dcorr.x1dcorr(["test_1_corrtag_a.fits", "test_1_corrtag_b.fits"], outdir="test/", update_input=True, find=True, verbosity=2)

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/costools/x1dcorr.py in x1dcorr(input, outdir, update_input, find, cutoff, location, extrsize, verbosity)
    183                     location=locn, extrsize=extrsz,
    184                     find_target={"flag": find, "cutoff": cutoff},
--> 185                     verbosity=verbosity)
    186 
    187 

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/calcos/x1d.py in extractSpec(inlist, outdir, update_input, location, extrsize, find_target, verbosity)
    205                            x1d_ab_list[i])
    206             is_wavecal = makeFltCounts(cal_ver, corrtag_list[i],
--> 207                                        flt_list[i], counts_list[i])
    208             extract.extract1D(flt_list[i], counts_list[i], x1d_ab_list[i],
    209                               location=location, extrsize=extrsize,

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/calcos/x1d.py in makeFltCounts(cal_ver, corrtag, flt, counts)
    446                 reffiles["brftab"])
    447     dq_array = timetag.doDqicorr(events, corrtag, info, switches, reffiles,
--> 448                                  phdr, headers[1], minmax_shift_dict)
    449 
    450     timetag.writeImages(x, y, epsilon, dq,

TypeError: doDqicorr() missing 2 required positional arguments: 'traceprofile' and 'gti'
```

I think I will be able to run calcos instead as a work around, but it would be nice to be able to use x1dcorr directly in the future so that I don't have to worry about asn files and such.

**Comment by parkus** [comment]
Ah, actually I see that `calcos` does not need to be run with an asn file as an argument; providing a corrtag produced by splittag seems to work fine! The Data Handbook does mention using `x1dcorr` though, so might be good to either remove that from the handbook or make sure `x1dcorr` works.

**Comment by stscirij** [comment]
Glad you spotted that calcos doesn't need an association file to run, you can feed it rawtags or corrtags depending where you are in the processing.  To be honest our costools needs some work - we've made some improvements in calcos that haven't always been reflected in costools/x1dcorr.

**Comment by Rplesha** [comment]
@parkus I believe we removed mention of the `x1dcorr` task in the COS data handbook version 4.0. Could you point us to the section where you are still seeing it mentioned so we can make sure to update that in the next version?

**Comment by Rplesha** [comment]
It looks like you have figured it out, but there is some additional documentation about work-arounds for the `x1dcorr` task here: https://stsci.service-now.com/hst?id=kb_article&sys_id=feb1ccd9db24db80fb50f9baae9619d5

**Comment by parkus** [comment]
Ah, that is very helpful, thank you @Rplesha . I should have checked the KB. 

The mention of x1dcorr in the DHB is in section 5.4, with the sentence "Next, the two sub-exposures should be extracted with x1dcorr either as a separate task or by running calcos from the corrtag file." https://hst-docs.stsci.edu/cosdhb/chapter-5-cos-data-analysis/5-4-working-with-time-tag-data

**Comment by Rplesha** [comment]
Thank you! We will make sure to update in our next data handbook release.
