### ISSUE TITLE
Astropy deprecated call

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/costools#4]
Hi @philhodge,
(cc @stsci-hack)
 
A quick scan of our entire codebase returned the usage of `astropy.io.fits.new_table` in the `costools.timefilter` module here:

https://github.com/spacetelescope/costools/blob/d8aefbf327b2d1ec3a4f476e4544e034a54f83d0/lib/costools/timefilter.py#L1083

**Comment by paultheastronomer** [comment]
Hi @jhunkeler, I have corrected this bug and created a pull request.
